name: spark-client
base: core20
version: '0.1'
summary: Client side scripts to submit Spark jobs to a cluster.
description: |
  The spark-client snap includes the scripts spark-submit, spark-shell, pyspark and other tools for managing Apache Spark jobs.

grade: stable
confinement: strict

apps:
  spark-submit:
    command: bin/spark-submit
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-amd64
      PATH: $JAVA_HOME/bin:$PATH
    plugs:
        - network
        - network-bind
        - network-control
        - home
  spark-shell:
    command: bin/spark-shell
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-amd64
      PATH: $JAVA_HOME/bin:$PATH
    plugs:
        - network
        - network-bind
        - network-control
        - home
  pyspark:
    command: bin/pyspark
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-amd64
      PATH: $JAVA_HOME/bin:$PATH
      PYTHONPATH: $PYTHONPATH:$SNAP/usr/lib/python3/dist-packages
    plugs:
        - network
        - network-bind
        - network-control
        - home

parts:
  spark:
    plugin: nil
    build-packages:
        - ca-certificates
        - ca-certificates-java
        - openjdk-11-jre-headless
        - python3
        - wget
    stage-packages:
        - openjdk-11-jre-headless
    override-build: |
        SPARK_VERSION='3.3.0'
        SPARK_HADOOP_VERSION='3'
        AWS_JAVA_SDK_BUNDLE_VERSION='1.11.874'
        HADOOP_AWS_VERSION='3.2.2'
        wget https://downloads.apache.org/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop${SPARK_HADOOP_VERSION}.tgz
        tar -zxf spark-${SPARK_VERSION}-bin-hadoop${SPARK_HADOOP_VERSION}.tgz
        cd spark-${SPARK_VERSION}-bin-hadoop${SPARK_HADOOP_VERSION}/jars
        wget https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/${AWS_JAVA_SDK_BUNDLE_VERSION}/aws-java-sdk-bundle-${AWS_JAVA_SDK_BUNDLE_VERSION}.jar
        wget https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/${HADOOP_AWS_VERSION}/hadoop-aws-${HADOOP_AWS_VERSION}.jar
        cd ..
        mkdir -p $SNAPCRAFT_PRIME/bin
        cp -r bin/* $SNAPCRAFT_PRIME/bin/
        mkdir -p $SNAPCRAFT_PRIME/jars
        cp -r jars/* $SNAPCRAFT_PRIME/jars/
        mkdir -p $SNAPCRAFT_PRIME/python
        cp -r python/* $SNAPCRAFT_PRIME/python/
    override-prime: |
        snapcraftctl prime
        rm -vf usr/lib/jvm/java-11-openjdk-*/lib/security/blacklisted.certs
